### PR TITLE
[Feature 13] Generate JavaDoc documents and correct JavaDocs with missing tags

### LINKED ISSUE #32: [Feature 13] Generate JavaDoc documents and correct JavaDocs with missing tags
don't approve yet

### PR DESCRIPTION
**Pull request by aricasas**

### CODE REVIEW

**Review by katarinaavucic — DISMISSED** [review]
Yay! So many files.

**Review by YinLingithub — DISMISSED** [review]
Cool

**Review by luluwuwu — DISMISSED** [review]
Very good

**Review by YinLingithub — APPROVED** [review]
Approve

**Review by katarinaavucic — APPROVED** [review]
Looks good! :D

**Review by luluwuwu — APPROVED** [review]
ok nice

**Pull request merged**
