### PR TITLE
[Feature 8] Improve Entity Documentation and Testing

### LINKED ISSUE #10: [Feature 8]  Improve Entity Documentation And Testing
Write better Javadocs and more tests for the entities that cover edge cases

### PR DESCRIPTION
**Pull request by katarinaavucic**
Added Javadocs and more testing for our base entities, to ensure that everything is tested properly! Let me know if anything seems weak (needs more testing) or if there is anything else you would like me to add.

### CODE REVIEW

**Review by YinLingithub — DISMISSED** [review]
I didn't see any problem. Very clear Javadocs!

**Review by aricasas — COMMENTED** [review]
All looking good!

**Review by YinLingithub — DISMISSED** [review]
Just giving Approval again because nothing changed.

**Review by luluwuwu — DISMISSED** [review]
I'm still thinking about adding a parameter in Expense, but I will approve for now as requested.

**Comment by katarinaavucic** [comment]
> I'm still thinking about adding a parameter in Expense, but I will approve for now as requested.

If you are adding a parameter in Expense you will need to add it in your use case and resolve conflicts with the one in main anyways. It is no different than if I were to do it, and you can reference how Ari changed SessionStorage if need be.

**Review by aricasas — DISMISSED** [review]
Everything looks good!

**Review by aricasas — APPROVED** [review]
Approved again

**Review by luluwuwu — APPROVED** [review]
approved

**Review by YinLingithub — APPROVED** [review]
Approved again.

**Pull request merged**
