### PR TITLE
Change file chooser in save button from Main Menu to display "Save" instead of "Open"

### LINKED ISSUE #45: Save session opens "open" window

### PR DESCRIPTION
**Pull request by aricasas**

### CODE REVIEW

**Review by YinLingithub — APPROVED** [review]
Wow, didn't expect this change would only be one line of code.
Looks good to me!

**Comment by aricasas** [comment]
Yep, the thing was already working, just that the file chooser displayed the word "Open" instead of "Save", but it still allowed you to save by typing a filename, so the code stays the same and I just needed to switch the function call to one that would display "Save" instead

**Review by katarinaavucic — APPROVED** [review]
Nice!

**Review by luluwuwu — COMMENTED** [review]
perfect

**Review by luluwuwu — APPROVED** [review]
I meant to approve it lol

**Pull request merged**
