### PR TITLE
Corrected casts in MonthlyMenuV constructor so that they don't throw a ClassCastException

### LINKED ISSUE #16: ClassCastException thrown in MonthlyMenuV constructor
Lines 93-96 on MonthlyMenuV cause a ClassCastException to throw.
```
Object[] expenseData = controller.getOutput(session, monthID).getExpenseData().toArray();
Object[] categoryData = controller.getOutput(session, monthID).getCategoryData().toArray();
JTable expenseTable = getExpenseTable((Expense[]) expenseData);
JTable categoryTable = getCategoryTable((Category[])categoryData);
```

The casts to Expense[] and Category[] fail

### PR DESCRIPTION
**Pull request by aricasas**
Changed the casts from ArrayLists to arrays to be manually done, to fix a ClassCastException that was being thrown in the MonthlyMenuV constructor.

### CODE REVIEW

**Review by katarinaavucic — APPROVED** [review]
Looks good!

**Review by YinLingithub — APPROVED** [review]
Thanks...

**Comment by luluwuwu** [comment]
Yay Nice!

**Review by luluwuwu — APPROVED** [review]
Approved

**Pull request merged**
