### PR TITLE
Update generated JavaDoc documentation

### LINKED ISSUE #63: Update generated JavaDoc documentation
Update the generated HTML documents containing the JavaDoc documentation to include all the new code changes since we last generated it

### PR DESCRIPTION
**Pull request by aricasas**
This PR fixes a couple mistakes in our JavaDoc and updates the generated JavaDoc website to contain our new factory classes and to contain our new class names.

### CODE REVIEW

**Review by katarinaavucic — APPROVED** [review]
Yay!!!!!

**Review by YinLingithub — COMMENTED** [review]
Is there a reason why the Javadoc/report is much less than before? (you've deleted 17914 and added 10427)

**Review by luluwuwu — APPROVED** [review]
Good

**Comment by aricasas** [comment]
I think it's because a lot of the files are being just modified instead of deleted

**Comment by YinLingithub** [comment]
> I think it's because a lot of the files are being just modified instead of deleted

But I would imagine the number of lines added will be more than number of lines deleted right? As we have many more classes in the entities package.

**Comment by aricasas** [comment]
Tbh I don't really know, I checked and all of our classes are there with their new names, including the factory classes. Maybe it's just that the HTML got generated differently or something

**Comment by YinLingithub** [comment]
> Tbh I don't really know, I checked and all of our classes are there with their new names, including the factory classes. Maybe it's just that the HTML got generated differently or something

I briefly took a look through all the files, and found that there were some files for the tests but they are deleted. Maybe it's those files?

**Review by YinLingithub — APPROVED** [review]
Looks good!

**Pull request merged**
